### ISSUE TITLE
Is there a way to set a Loquat output as optional?

### ISSUE THREAD

**Issue by agarciamontoro** [era7bio/asdfjkl#10]
There is an output file that may not exist depending on the input of the analysis pipeline, so loquat complaints when it tries to upload it.

The file is this one: https://github.com/era7bio/asdfjkl/blob/master/src/main/scala/loquats/allinone.scala#L112 and its existence depends on this condition of each cluster: https://github.com/era7bio/repseqmiodx/blob/master/src/main/scala/umi/ReadsProcessing.scala#L74

My question: is there a way to tell loquat that an output may not exist?

**Comment by laughedelic** [comment]
Yes, there is a way:

1. _always_ create output files. Even if you're not going to write anything there. Loquat will check on upload whether they exist and whether they are empty. You cannot do anything with the first check, but
2. you can _skip empty outputs_ upload by overriding `skipEmptyResults = true` in the config 👌 

For the reference: https://github.com/ohnosequences/loquat/pull/59

**Comment by agarciamontoro** [comment]
Thanks!
