### ISSUE TITLE
Can we launch two pipelines at the same time?

### ISSUE THREAD

**Issue by agarciamontoro** [era7bio/asdfjkl#4]
I thin we cannot (I just tried to launch two experiments from webmiodx interface and nothing occured) because of the loquat configuration, but I'm not really sure. @eparejatobes, any idea?

**Comment by eparejatobes** [comment]
No, we can't.

**Comment by agarciamontoro** [comment]
But we definitely should... :( Is this a structural problem from loquat or do you think it is feasible to implement a workaround to do this?

**Comment by eparejatobes** [comment]
Options:

- Modify Loquat so that two instances of the same jar can coexist. This needs at least changing the way AWS resources are created
- Keep one and only one Loquat instance, and send messages to the input SQS queue. Worker instances could kill themselves once they finish a job and then decrease the desired capacity of the AutoScaling group.
- ...

**Comment by laughedelic** [comment]
You can launch several loquats from the same jar, but you need to set different `loquatName`s explicitly in the configuration. All resource names have `loquatName` in as a prefix.

**Comment by agarciamontoro** [comment]
Then a quick solution to this problem would be to add a unique id (timestamp or something similar) to each loquat name, isn't it?

**Comment by laughedelic** [comment]
@agarciamontoro yep, I think so. At least it's worth a try.

**Comment by agarciamontoro** [comment]
We should do this as a quick fix, as we had one (bad) sample being analysed for several days and MIODx was not able to run any other experiment.

**Comment by agarciamontoro** [comment]
Also, a question, @laughedelic: is there a quick way to autofinish an instance after X hours from its start?

**Comment by laughedelic** [comment]
> We should do this as a quick fix

OK. I didn't notice that I'm assigned here. 

> is there a quick way to autofinish an instance after X hours from its start?

There are 2 timeout conditions that you can set in the loquat config:

https://github.com/ohnosequences/loquat/blob/e9e2d5dab91b95b67784cc3c9ce63f1010bb314f/src/main/scala/ohnosequences/loquat/configs/termination.scala#L72-L75

Is this what you're looking for?

**Comment by agarciamontoro** [comment]
> I didn't notice that I'm assigned here.

No no, don't worry, I didn't notice either you were assigned here, I'm doing it myself.

> Is this what you're looking for?

I think so, thank you! :clap:

**Comment by laughedelic** [comment]
> No no, don't worry, I didn't notice either you were assigned here, I'm doing it myself.

OK 👍 Ask me if you'll have any doubts. [`ResourceNames`](https://github.com/ohnosequences/loquat/blob/e9e2d5dab91b95b67784cc3c9ce63f1010bb314f/src/main/scala/ohnosequences/loquat/configs/resources.scala#L6) has a prefix parameter, and it's set to the [`loquatId`](https://github.com/ohnosequences/loquat/blob/e9e2d5dab91b95b67784cc3c9ce63f1010bb314f/src/main/scala/ohnosequences/loquat/configs/loquat.scala#L54) that you can change in the config.
